apiVersion: v2
name: calibre-web-automated
description: A deployment of Calibre Web Automated.
type: application
version: 1.0.0
appVersion: 1.0.0
annotations:
  org.opencontainers.image.source: https://github.com/jedaniels000/helm-cwa
icon: >-
  https://raw.githubusercontent.com/kovidgoyal/calibre/master/resources/images/lt.png
maintainers:
  - name: jedaniels000
    url: https://github.com/jedaniels000
