# Default values for calibre-web-automated (CWA).

# -- Port for CWA service/ingress.
servicePort: 8083

containers:
  cwa:
    image:
      # -- Image repository for CWA image.
      repository: crocodilestick/calibre-web-automated
      # -- Image pull policy for CWA image.
      pullPolicy: IfNotPresent
      # -- Image tag for CWA image.
      tag: "v4.0.6"
    # -- Additional volume mounts to add to the CWA container.
    # NOTE: If default PVC is enabled, you don't need to include
    # corresponding `volumeMount`s here as they're included by
    # default; these include `/config`, `/cwa-book-ingest`, and
    # `/calibre-library`.
    volumeMounts: []
    # -- Environment variables for CWA container.
    # @default -- See below
    env:
      # -- User ID in container.
      PUID: 1000
      # -- Ground ID in container.
      PGID: 1000
      # -- Timezone for CWA server. See:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      TZ: Etc/UTC

# This is for the secrets for pulling an image from a private
# repository more information can be found here:
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  # -- If true, enables ingress.
  enabled: false
  className: "nginx"
  annotations: {}
  hosts: []
    # - host: calibre-web-automated.local
    #   paths:
    #     - path: /
    #       pathType: Prefix
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

storage:
  # -- Size of storage to create/request (e.g. 10Gi)
  capacity: ""
  pv:
    # -- If true, creates the default local persistant volume.
    enabled: false
    # -- Local storage path for PV.
    path: ""
    # -- Hostname for node to which PV will be assigned.
    hostname: ""
  pvc:
    # -- If true, creates the default persistant volume claim.
    enabled: false

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout:
# https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout:
# https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

resources: {}

# -- Additional volumes on the output Deployment definition.
# NOTE: If default PVC is enabled, you don't need to include that
# volume here as it's included by default as `default-storage`.
volumes: []

nodeSelector: {}

tolerations: []

affinity: {}
