# Default values for calibre-web-automated (CWA).

# -- Port for CWA service/ingress.
servicePort: 8083

containers:
  cwa:
    enabled: true
    image:
      # -- Image repository for CWA image.
      repository: crocodilestick/calibre-web-automated
      # -- Image pull policy for CWA image.
      pullPolicy: IfNotPresent
      # -- Image tag for CWA image.
      tag: "v4.0.6"
    # -- Volume claim spec.
    volumeClaims:
      config:
        mountPath: /config
        storage: 100Mi
      calibre-library:
        mountPath: /calibre-library
        storage: 1Gi
    # -- Additional volume mounts to add to the CWA container.
    extraVolumeMounts: []
    # -- Environment variables for CWA container.
    # @default -- See below
    env:
      # -- User ID in container.
      PUID: 1000
      # -- Ground ID in container.
      PGID: 1000
      # -- Timezone for CWA server. See:
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      TZ: Etc/UTC
    # -- Security context for the CWA container.
    # @default -- See below
    securityContext:
      # -- UID to run as.
      runAsUser: 1000
      # -- GID to run as.
      runAsGroup: 1000
      # -- Whether or not to run as non-root.
      runAsNonRoot: true
      # -- Whether or not to allow escalation of privileges.
      allowPrivilegeEscalation: false

# -- Pod security context.
securityContext:
  fsGroup: 1000

# This is for the secrets for pulling an image from a private
# repository more information can be found here:
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# -- Additional entries to /etc/hosts for DNS resolution. Check K8s
# documentation for additional info.
hostAliases: []

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout:
# https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout:
# https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

resources: {}

# -- Additional volumes on the output Deployment definition.
# NOTE: If default volume claims are enabled, you don't need to include those
# here.
volumes: []

nodeSelector: {}

tolerations: []

affinity: {}
