apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calibre-web-automated.fullname" . }}
  labels:
    {{- include "calibre-web-automated.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "calibre-web-automated.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "calibre-web-automated.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- $cwa := .Values.containers.cwa }}
        - name: {{ .Chart.Name }}
          image: "{{ $cwa.image.repository }}:{{ $cwa.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $cwa.image.pullPolicy }}
          ports:
            - containerPort: 8083
          env:
            {{- range $key, $value := $cwa.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.storage.pvc.enabled }}
            - name: default-storage
              mountPath: /config
              subPath: config
            - name: default-storage
              mountPath: /cwa-book-ingest
              subPath: cwa-book-ingest
            - name: default-storage
              mountPath: /calibre-library
              subPath: calibre-library
            {{- end }}
            {{- with $cwa.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.storage.pvc.enabled }}
        - name: default-storage
          persistentVolumeClaim:
            claimName: {{ include "calibre-web-automated.fullname" . }}
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- include "calibre-web-automated.nodeAssignment" . | nindent 6 }}
