apiVersion: v1
kind: Service
metadata:
  name: {{ include "calibre-web-automated.fullname" . }}-headless
  {{- with .Values.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "calibre-web-automated.labels" . | nindent 4 }}
spec:
  # Headless service to support StatefulSet
  clusterIP: None
  ports:
    - port: 8083
      name: http
  selector:
    {{- include "calibre-web-automated.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calibre-web-automated.fullname" . }}
  {{- with .Values.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "calibre-web-automated.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.servicePort | default 80 }}
      targetPort: 8083
      name: http
  selector:
    {{- include "calibre-web-automated.selectorLabels" . | nindent 4 }}
