apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "calibre-web-automated.fullname" . }}
  {{- with .Values.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "calibre-web-automated.labels" . | nindent 4 }}
spec:
  # Required for StatefulSets: Ties pods to a Headless Service
  serviceName: {{ include "calibre-web-automated.fullname" . }}-headless
  # Hardcoded to max of 1 for SQLite safety
  replicas: {{ min 1 (.Values.replicaCount | int) }}
  selector:
    matchLabels:
      {{- include "calibre-web-automated.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "calibre-web-automated.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- $cwa := .Values.containers.cwa }}
        - name: {{ .Chart.Name }}
          image: "{{ $cwa.image.repository }}:{{ $cwa.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $cwa.image.pullPolicy }}
          {{- with $cwa.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 8083
          env:
            {{- range $key, $value := $cwa.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- with $cwa.envFrom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- range $name, $volumeClaim := $cwa.volumeClaims }}
            - name: {{ $name }}
              mountPath: {{ $volumeClaim.mountPath }}
            {{- end }}
            {{- with $cwa.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- include "calibre-web-automated.nodeAssignment" . | nindent 6 }}

  volumeClaimTemplates:
    {{- range $name, $volumeClaim := .Values.containers.cwa.volumeClaims }}
    - metadata:
        name: {{ $name }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- with $volumeClaim.storageClassName }}
        storageClassName: {{ . }}
        {{- end }}
        resources:
          requests:
            storage: {{ $volumeClaim.storage }}
    {{- end }}
