apiVersion: v1
kind: Service
metadata:
  name: {{ include "calibre-web-automated.fullname" . }}
  labels:
    {{- include "calibre-web-automated.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.servicePort | default 8083 }}
      targetPort: 8083
  selector:
    {{- include "calibre-web-automated.selectorLabels" . | nindent 4 }}
